/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ChangementMDP': RouteRecordInfo<'/ChangementMDP', '/ChangementMDP', Record<never, never>, Record<never, never>>,
    '/connexion': RouteRecordInfo<'/connexion', '/connexion', Record<never, never>, Record<never, never>>,
    '/infos-legales': RouteRecordInfo<'/infos-legales', '/infos-legales', Record<never, never>, Record<never, never>>,
    '/journal': RouteRecordInfo<'/journal', '/journal', Record<never, never>, Record<never, never>>,
    '/modifier-avatar': RouteRecordInfo<'/modifier-avatar', '/modifier-avatar', Record<never, never>, Record<never, never>>,
    '/profil': RouteRecordInfo<'/profil', '/profil', Record<never, never>, Record<never, never>>,
    '/reves/': RouteRecordInfo<'/reves/', '/reves', Record<never, never>, Record<never, never>>,
    '/reves/[id]': RouteRecordInfo<'/reves/[id]', '/reves/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/reveurs/[id]': RouteRecordInfo<'/reveurs/[id]', '/reveurs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/saisir-reve': RouteRecordInfo<'/saisir-reve', '/saisir-reve', Record<never, never>, Record<never, never>>,
    '/welcolmeuser': RouteRecordInfo<'/welcolmeuser', '/welcolmeuser', Record<never, never>, Record<never, never>>,
  }
}
